### ISSUE TITLE
Can't export local map with styles that are not assigned to theme

### ISSUE THREAD

**Issue by lukasoppermann** [JulianWels/atlas#1]
Hey, as I mentioned on twitter, this is a great plugin. 👍 

## Issue
When I have styles that are not assigned to a theme, the plugin does not let me export the local map. It does not seem to matter if the colors are private (prefixed with a "_") or published but not added to a theme.

You can find a Figma file with the setup in this file: https://www.figma.com/file/zcKtsKdjoHHXtqttx47tbH/Bug-report?node-id=0%3A1

<img width="1196" alt="Screenshot 2021-01-29 at 10 45 18" src="https://user-images.githubusercontent.com/813754/106259201-305f6b00-621f-11eb-9ebd-394aa2dd7d4d.png">
<img width="433" alt="Screenshot 2021-01-29 at 10 45 26" src="https://user-images.githubusercontent.com/813754/106259208-32292e80-621f-11eb-807e-5697b9daee64.png">
<img width="408" alt="Screenshot 2021-01-29 at 10 45 32" src="https://user-images.githubusercontent.com/813754/106259209-32c1c500-621f-11eb-9804-005cba85dd2b.png">

## Use case
A very typical use case is that you define a theme in a file where you also define base colors. However you only want to export the theme colors, the base colors are supposed to just be internal (prefixed with "_" to not be published) or not part of a theme at least.

**Comment by JulianaGaibler** [comment]
Thanks for digging into it and giving such a detailed error description. I really appreciate it!

**Comment by lukasoppermann** [comment]
Thank you for fixing it. Works great. 👍

**Comment by lukasoppermann** [comment]
Just in case somebody comes here. Sometimes the issue is that you changed styles and they are not published. This also creates an "Unkown error".
