### ISSUE TITLE
Include effect styles into themes

### ISSUE THREAD

**Issue by lukasoppermann** [JulianWels/atlas#2]
Hey @JulianWels,

At my company I am currently working on the light and dark themes using your fantastic plugin. With the fix from #1 it works like a charm now.

I did run into an issue though: Effects / Shadows / Elevation is different for dark and light mode (black shadows don't work well on black BGs 😉 ). It would be great if the plugin could integrate effect styles using the same theme name as well. (E.g. Light / Elevation / 01 dp → Dark / Elevation / 01 dp)

**Comment by JulianaGaibler** [comment]
Hi! Theming should work for color-, effect- and text-styles and I can't reproduce the issue in my test project.

Could you provide steps to reproduce or some screenshots, so we can narrow it down?

**Comment by lukasoppermann** [comment]
Hey @JulianWels I just never tried it. I didn't see it in the video tutorial, so I assumed it was not supported. 😉 
Awesome, to learn it is. Works perfect. 👍
