### ISSUE TITLE
More helpful error messages

### ISSUE THREAD

**Issue by lukasoppermann** [JulianWels/atlas#4]
Hey,

we just ran into this error:
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/813754/132202534-b60c43e0-6f2b-497a-b895-f926d2c184d2.png)

The problem actually was that we did not publish the recent changes from the library.

It would be great if you could either detect the issue better and provide a good error message or just profile a list of common issue:

E.g. 
### Make sure to check the following things
- no unpublished styles in your library
- ....

**Comment by JulianaGaibler** [comment]
Hi!
Thanks for creating an issue for this and using Atlas! I'm working on a larger update that also includes improved error messages and error handling. If you come across other confusing or generic error messages let me know.

**Comment by JulianaGaibler** [comment]
If there are error messages that are still unclear, feel free to re-open this issue.
