### ISSUE TITLE
Command palette command for toggling themes

### ISSUE THREAD

**Issue by lukasoppermann** [JulianWels/atlas#6]
Hey,

what I really like about the "lights" plugin is the ability to quickly toggle between dark & light mode via the command palette.

Of course its a bit easier if you only allow dark & light, but I think atlas could introduce a "toggle next theme" command.

**I would imagine it like this:**
1. User selects frames
2. cmd + p 
3. start typing "at" -> suggests "atlas> next theme"
4. hit return
5. atlas toggles the next theme.

### Benefits
- For users with just light and dark mode it works exactly like a toggle
- For users with more than two modes it still works fine

**Comment by JulianaGaibler** [comment]
Also looking into this one, might work a little different though, let's see!

**Comment by JulianaGaibler** [comment]
Heya 👋 

It works a bit differently than you suggested. The trouble with a proper 'next' option is that it becomes difficult to understand what that would do with more complex or multiple themes.

You still have to specify the theme you want to switch from and to from the quick-actions menu, but I made sure that only options that are relevant to the selection are listed. In the case of strictly light-dark themes, you can simply press enter several times in a row without thinking, and Figma remembers the selection as well.

If this doesn't provide the convenience you hoped for, I can try to look at it again.

**Comment by lukasoppermann** [comment]
Hey,
nice. It's a bit more effort than I would love.

What I don't understand is, why do you need the `from` part?

**Comment by lukasoppermann** [comment]
Just @JulianWels making sure you see this. 😄
